### ISSUE TITLE
global name 'keys'is not defined

### ISSUE THREAD

**Issue by darkpixel** [progrium/keychain.io#13]
```
09:05:53 [aaron:~] 3s $ curl -s ssh.keychain.io/aaron@heyaaron.com/all
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/eventlet/wsgi.py", line 382, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "keychain/app.py", line 115, in all_keys
    keys_ = [lookup_key(email, key) for key in keys[email]]
NameError: global name 'keys' is not defined
09:06:26 [aaron:~] $ 
```

**Comment by jbrooksuk** [comment]
@progrium is this something we can get fixed?

**Comment by jbrooksuk** [comment]
Duplicate of #2.
