### ISSUE TITLE
error on clicking confirmation link

### ISSUE THREAD

**Issue by nidheeshdas** [progrium/keychain.io#15]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/eventlet/wsgi.py", line 382, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1701, in **call**
    return self.wsgi_app(environ, start_response)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "keychain/app.py", line 94, in confirm_action
    action[0](*action[1])
  File "keychain/app.py", line 43, in upload_key
    k.set_contents_from_string(key.strip())
  File "/app/.heroku/python/lib/python2.7/site-packages/boto/s3/key.py", line 1124, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/app/.heroku/python/lib/python2.7/site-packages/boto/s3/key.py", line 926, in set_contents_from_file
    provider = self.bucket.connection.provider
AttributeError: 'NoneType' object has no attribute 'connection'

**Comment by takinbo** [comment]
@progrium I have submitted a PR that fixes this. Maybe this could get deployed to production soon?

**Comment by michaelcontento** [comment]
+1

**Comment by faeton** [comment]
+1

**Comment by fikovnik** [comment]
+1

**Comment by ayr-ton** [comment]
+1

**Comment by adfernandes** [comment]
:+1:

**Comment by adumont** [comment]
+1

**Comment by shashank64** [comment]
+1
Is there a fork/alternative server available?

**Comment by ebuildy** [comment]
The service is dead I think :/
